{{- if .Values.digital_ocean.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-node-pool-operator-do.fullname" . }}
  namespace: {{ .Release.Namespace  }}
type: Opaque
stringData:
  cluster_id: {{ required "A digital ocean cluster id is required!" .Values.digital_ocean.cluster_id  }}
  token: {{ required "A digital ocean API token is required!" .Values.digital_ocean.token  }}
{{- end }}