{{- if .Values.digitalOcean.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-node-pool-operator-do.fullname" . }}
  namespace: {{ .Release.Namespace  }}
type: Opaque
stringData:
  clusterId: {{ required "A digital ocean cluster id is required!" .Values.digitalOcean.clusterId  }}
  token: {{ required "A digital ocean API token is required!" .Values.digitalOcean.token  }}
{{- else }}
{{- $_ := required "A digital ocean cluster id secret is required!" .Values.digitalOcean.clusterIdSecret }}
{{- $_ := required "A digital ocean cluster id secret name is required!" .Values.digitalOcean.clusterIdSecret.name }}
{{- $_ := required "A digital ocean cluster id secret key is required!" .Values.digitalOcean.clusterIdSecret.key }}
{{- $_ := required "A digital ocean token secret is required!" .Values.digitalOcean.tokenSecret }}
{{- $_ := required "A digital ocean token secret name is required!" .Values.digitalOcean.tokenSecret.name }}
{{- $_ := required "A digital ocean token secret key is required!" .Values.digitalOcean.tokenSecret.key }}
{{- end }}