name: Test

on:
  push:
    branches: ["master"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "k8s-managed-node-pool/**"
      - "k8s-managed-node-pool-crdgen/**"
      - "k8s-managed-node-pool-do/**"
  pull_request:
    branches: ["master"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "k8s-managed-node-pool/**"
      - "k8s-managed-node-pool-crdgen/**"
      - "k8s-managed-node-pool-do/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
